### ISSUE TITLE
Server Timing headers ms format

### ISSUE THREAD

**Issue by rochoa** [ChromeDevTools/devtools-frontend#14]
Correct me if I'm wrong, but as per discussed here https://twitter.com/rochoa/status/829265498441392128, it seems the format for the Server-Timing headers is not correct.

I'm wondering if a patch like the following one could fix the issue:

```patch
diff --git a/front_end/network/RequestTimingView.js b/front_end/network/RequestTimingView.js
index 9c7a2773..f67408e3 100644
--- a/front_end/network/RequestTimingView.js
+++ b/front_end/network/RequestTimingView.js
@@ -284,7 +284,7 @@ Network.RequestTimingView = class extends UI.VBox {
       }
       var label = tr.createChild('td').createChild('div', 'network-timing-bar-title');
       if (typeof serverTiming.value === 'number')  // a metric timing value is optional
-        label.textContent = Number.secondsToString(serverTiming.value, true);
+        label.textContent = Number.millisToString(serverTiming.value, true);
     }

     /**
```

BTW, thanks for this feature 😄 .

**Comment by wwwillchen** [comment]
@allada can you take a look?

**Comment by paulirish** [comment]
@rochoa yeah good call. I think we should make the change. (and break people for a few weeks).

cc @sroussey does this patch sound good to you?
also cc @igrigorik

**Comment by sroussey** [comment]
Yes, though it bothers me that i tested with seconds the whole time.

**Comment by paulirish** [comment]
Patch is up here: https://codereview.chromium.org/2689833002

**Comment by allada** [comment]
+1 Thanks!

**Comment by paulirish** [comment]
This fix has landed: https://codereview.chromium.org/2689833002  You can try it out in Chrome Canary or a fresh build of chromium.

We're not sure if we will merge this change to beta. If we do, it won't be in stable until mid-march. (4 weeks from now). 
If we don't merge, it will be in stable in late april (10 weeks from now).

In either case, folks who have already adopted this **will have to make the transition**, once they see all their timings jump down to sub-millisecond numbers. It's a little awkward, but we appreciate everyone's patience. 
(Alternatively one _could_ parse the useragent string and provide ms to chrome 58, and s to if <58.)

**Comment by rochoa** [comment]
Just tested it in Chrome Canary 👍 .

Thank you for taking care of this one so quickly, especially considering the possible impact on existing users.
