### ISSUE TITLE
InspectorBackend is not defined

### ISSUE THREAD

**Issue by abnerCrack** [ChromeDevTools/devtools-frontend#140]
When I try to access it.

![image](https://user-images.githubusercontent.com/8336662/59042068-60b8ff80-88ac-11e9-849f-764d32317463.png)

http://localhost:8080/devtools/front_end/inspector.html?ws=localhost:9000/ios_2374d3ef48c7e69ad9c8df9a4244ae7316c00c99/ws://127.0.0.1:9101/devtools/page/1&amp;remoteFrontend=true

How can i fix it

**Comment by a1ph** [comment]
It is fixed in 77.0.3815.0
https://chromiumdash.appspot.com/commit/3e23615b10ee1bc286cf15d30a4343facc6a88c7

**Comment by abnerCrack** [comment]
@a1ph  Thank you for your answer，But I've pulled out the latest code ，problem and it's still there
I am confused。
