### ISSUE TITLE
ARIAProperties.js is missing

### ISSUE THREAD

**Issue by ak239** [ChromeDevTools/devtools-frontend#141]
Accessibility module requires `ARIAProperties.js`, this file is generated during build process. I am wondering, can we have it in this repository the same way as we have `SupportedCSSProperties.js`?

**Comment by paulirish** [comment]
How about we put it in front_end/accessibility ?

**Comment by ak239** [comment]
It will be perfect.

**Comment by paulirish** [comment]
https://cdn.jsdelivr.net/npm/chrome-devtools-frontend@1.0.669430/front_end/accessibility/ARIAProperties.js
