### ISSUE TITLE
How to build this project?

### ISSUE THREAD

**Issue by tedpenk** [ChromeDevTools/devtools-frontend#143]
I need build my own devtools-frontend, but I can't find any command that can do this job in package.json, Please tell me what should I do?

**Comment by tedpenk** [comment]
Solved with https://github.com/ChromeDevTools/devtools-protocol, so close this issues.

**Comment by jytx** [comment]
I want to build frontend too,but I do not find how to build it ,can u tell me how to build? @tedpenk
