### ISSUE TITLE
Question. How to get all timeline data

### ISSUE THREAD

**Issue by denar90** [ChromeDevTools/devtools-frontend#19]
Hey guys. I have some question about getting trace data in e.g. json format.
I have opened timeline and have access to `_tracingModelBackingStorage` via `Timeline.TimelinePanel.instance()._tracingModelBackingStorage`.
`_tracingModelBackingStorage` is `Bindings.TempFileBackingStorage` instance, if I got it correctly, so I have access to file `Timeline.TimelinePanel.instance()._tracingModelBackingStorage._file` but unfortunately it can't be read using `FileReader`

```js
const reader = new FileReader();
reader.readAsBinaryString(Timeline.TimelinePanel.instance()._tracingModelBackingStorage._file);
```

Maybe there are some way to get `Bindings.TempFile` instance which has `read` method?

---

Also I can get data using either `Timeline.TimelinePanel.instance()._model.records()` which is array of `TimelineModel.TimelineModel.Record` or `Timeline.TimelinePanel.instance()._tracingModel._devToolsMetadataEvents` which is array of `SDK.TracingModel.Event`.
Maybe using this way I there are some API which I can use to transfer data.
Otherwise I will jsut parse data using my own logic.

Thanks :)

**Comment by paulirish** [comment]
Hey @denar90! :)

You can check out https://github.com/paulirish/devtools-timeline-model which exposes that model easily for you. (Also the `latestbump` branch there is almost up to date with things... )

Using the timeline-model is perfect for something like "give me the breakdown across activities (layout, paint, js compile, js execution, etc) over this time range".

Alternatively you can process the raw trace yourself.  For very basic things, doing it yourself is fairly reasonable (just copy trace-of-tab.js from Lighthouse and work from there).

**Comment by paulirish** [comment]
Oh I think I misunderstood. You want to extract the raw json trace from inside of the devtools. :)  

Without looking I imagine you could monkeypatch an `addEvent` sort of method in sdk/tracingmodel. 

But yeah trying to read from the backing storage also sounds promising. :)

**Comment by denar90** [comment]
@paulirish thx! I'll try :)
