### ISSUE TITLE
user timing in performance timeline epoch

### ISSUE THREAD

**Issue by cvazac** [ChromeDevTools/devtools-frontend#22]
steps:
-navigate to any webpage with the attached tampermonkey script
-go to the performance tab of dev tools
-click the reload button from the performance tab
-when the load completes, expand the "user timing" section and note the left edge of the `m1` horizontal bar

![image](https://cloud.githubusercontent.com/assets/9857665/26218364/904498c2-3bbf-11e7-88f0-622d867cce57.png)

When you create a user-timing measure with neither start nor end mark, `navigationStart` is used as the inferred start time of the measure:
https://www.w3.org/TR/user-timing/#dom-performance-measure

I'm consistently seeing the left edge line up with between 35 and 65 ms. I think `navigationStart`, and consequently all user timing measures, should line up with 0 in the timeline.

[user-timing-measure.js.user.js.zip](https://github.com/ChromeDevTools/devtools-frontend/files/1011955/user-timing-measure.js.user.js.zip)

**Comment by cvazac** [comment]
Also, and likely related, the red "load event" vertical line is suspiciously off by about the same amount. 

Example:
![image](https://cloud.githubusercontent.com/assets/9857665/26258640/64e298f8-3c7a-11e7-8037-9dbe2fbcada0.png)

`performance.now()` in my `window.onload` handler was 3857.225.

![image](https://cloud.githubusercontent.com/assets/9857665/26258707/af4ed30c-3c7a-11e7-9a6c-5495c8bd6949.png)

You can see that both items are ~110ms off.

**Comment by phistuck** [comment]
Please, use https://crbug.com for reporting issues and feature requests.

**Comment by cvazac** [comment]
logged here: https://bugs.chromium.org/p/chromium/issues/detail?id=730131
