### ISSUE TITLE
[Question] What does this disclaimer in panel.js say?

### ISSUE THREAD

**Issue by imvetri** [ChromeDevTools/devtools-frontend#28]
Is the orignal organization is Apple and its not the Google's copyright?

Below is the screenshot of copyright in panel.js
![chrome_development_history_from_copyright](https://user-images.githubusercontent.com/6542274/28249491-6565f0cc-6a74-11e7-9cfc-e114a36e715f.PNG)

I also saw the same copyright in 16+ other files. Reason I brought up this is the wikipedia says the otherwise.  [https://en.wikipedia.org/wiki/Chromium_(web_browser)#2008](https://en.wikipedia.org/wiki/Chromium_(web_browser)#2008)
![chrome_development_history_from_wiki](https://user-images.githubusercontent.com/6542274/28249492-6a4356b6-6a74-11e7-96a7-568741b896bb.PNG)

**Comment by paulirish** [comment]
Much of devtools frontend began its life in the WebKit Web Inspector, which was shipped in Chromium, WebKit, Chrome, and Safari.

The standard license header within that project used an Apple copyright.  The WebKit wikipedia page is probably more useful in this case.
