### ISSUE TITLE
Export initiators in HAR format

### ISSUE THREAD

**Issue by mems** [ChromeDevTools/devtools-frontend#29]
Use a ["Custom Fields"](https://dvcs.w3.org/hg/webperf/raw-file/tip/specs/HAR/Overview.html) to store the request initiator (the custom field "MUST start with an underscore").

```
"entries": [
    {
        "pageref": "page_0",
        "startedDateTime": "2009-04-16T12:07:23.596Z",
        "time": 50,
        "request": {...},
        "response": {...},
        "cache": {...},
        "timings": {},
        "serverIPAddress": "10.0.0.1",
        "connection": "52492",
        "comment": "",
        "_initiator": {
            "type": "script",
            "stack": ...,
            "url": ...,
            "lineNumber": ...
        }
    }
]
```

See [`Protocol.Network.Initiator`](https://github.com/ChromeDevTools/devtools-frontend/blob/master/protocol.json)

**Comment by paulirish** [comment]
cc @allada  we didn't include initiator and priority in the new HARs? is it easy to add?

**Comment by allada** [comment]
This is something we can do. Because of the recent import I wanted to hold off on the super specific chrome stuff like initiator, but yes, it is something we'll likely do soon.

**Comment by allada** [comment]
Please continue discussion here: http://crbug.com/654536/
