### ISSUE TITLE
Element wrapping in "Elements" panel

### ISSUE THREAD

**Issue by LanceJernigan** [ChromeDevTools/devtools-frontend#31]
Currently, elements near the edge of the element panel are set to wrap to the next line.  When viewing a deeply nested element in a narrow inspector (docked to left/right), these elements become difficult to read because of the way they wrap.

![screen shot 2017-08-17 at 11 37 10 am](https://user-images.githubusercontent.com/13667572/29420639-80e97a5a-8340-11e7-8472-f02d45c73c2b.png)

Two potential solutions are:

1.  Set the elements panel to scroll horizontally keeping each element on a single line
2.  Set elements to wrap at parameters as opposed to the end of the line.

**Comment by paulirish** [comment]
You can toggle your solution no. 1 in devtools settings:
![image](https://user-images.githubusercontent.com/39191/29427256-1e2f9522-833e-11e7-90cb-18a506afa666.png)
