### ISSUE TITLE
Option for examining DOM elements the same way as other JS objects

### ISSUE THREAD

**Issue by brunnerh** [ChromeDevTools/devtools-frontend#32]
When a DOM element is returned from an expression in the console, the developer only has the hierarchical DOM view on the object as already present in the *Elements* panel. It would be nice to be able to inspect elements like any other JS object, so it is easier to examine custom functions, properties and the like.

A context menu option or something similar to switch between representations would work well, i think.

**Comment by paulirish** [comment]
`dir(elem)` is the preferred way. 

We've discussed a more rich object viewer where you can choose what sort of formatter you want.. but it hasn't materialized yet.

**Comment by paulirish** [comment]
(dir is part of https://developers.google.com/web/tools/chrome-devtools/console/command-line-reference )
