### ISSUE TITLE
"`document.registerElement` is not a function" error in non-Chrome browsers

### ISSUE THREAD

**Issue by cowchimp** [ChromeDevTools/devtools-frontend#35]
Hi.

I'm not sure if it is a design-goal of this project to be able to run the DevTools Frontend in other browsers.

I just tried running it in Firefox and in Microsoft Edge, and got an error related to `registerElement` not being available.
(In Firefox the message is `document.registerElement is not a function` and in Edge it's `Object doesn't support property or method 'registerElement'`)
I'm using [https://chrome-devtools-frontend.appspot.com/serve_file/@c1eefdc7467469d105724cf083c929496a774919/inspector.html](https://chrome-devtools-frontend.appspot.com/serve_file/@c1eefdc7467469d105724cf083c929496a774919/inspector.html).

If it's NOT a design goal to be able to run on other browsers- should this be stated clearly in the Readme?

Thanks.

**Comment by paulirish** [comment]
The DevTools frontend isn't intended to run in non-Chrome, that's correct.

It also comes with a lot of other concerns about its reusability, so that's why nothing was documented like this in the readme. If you want to use the frontend in a project, that's fine, but it's not designed for that. :)
