### ISSUE TITLE
How to generating 'SupportedCSSProperties.js'?

### ISSUE THREAD

**Issue by misakuo** [ChromeDevTools/devtools-frontend#4]
as title

**Comment by darwin** [comment]
this how I do it:
https://github.com/binaryage/dirac/blob/master/scripts/generate-supported-css-properties.sh

**Comment by misakuo** [comment]
Ohhhh... what's `$CSS_PROPERTIES_SOURCE` mean? is `protocol.json`?

**Comment by misakuo** [comment]
it's `CSSProperties.in`, found it on `config.sh`, thanks a lot~
