### ISSUE TITLE
[Help Wanted] Uncaught TypeError at WorkerManager

### ISSUE THREAD

**Issue by misakuo** [ChromeDevTools/devtools-frontend#6]
```
WorkerManager.js:89 Uncaught TypeError: this.target(...).workerAgent(...).setWaitForDebuggerOnStart is not a function_onSuspendStateChanged @ WorkerManager.js:89    
WebInspector.WorkerManager @ WorkerManager.js:48    
createTarget @ TargetManager.js:217    
_connectionEstablished @ Main.js:312    
_createConnection @ Main.js:289
```    
I cloned this repo and running a Http Server on directory `front_end`, but when I open `http://127.0.0.1:8080/inspector.html?ws=xxx`, the above error occurred.    
Is my operation wrong? what's the correct way to launch devtools?
sorry for the basic question.

**Comment by paulirish** [comment]
I'm not sure how you ended up with this exception. It would indicate that the workerAgents are not made. I guess you have a 404 of InspectorBackendCommands.js ?

**Comment by paulirish** [comment]
bit.ly/devtools-contribution-guide was recently updated. I would give that a shot with the new `npm run server` stuff.

**Comment by misakuo** [comment]
thanks for your help
