### ISSUE TITLE
how to use Protocol Monitor

### ISSUE THREAD

**Issue by xuzhanhh** [ChromeDevTools/devtools-frontend#66]
hi, i find Protocol Monitor was built 3 days ago. But i can't find the entrance of Protocol Monitor. thanks

**Comment by xuzhanhh** [comment]
![image](https://user-images.githubusercontent.com/20735181/37401858-7638ff12-27c4-11e8-8c9a-5058b5af7a38.png)

**Comment by paulirish** [comment]
You can enable it in experiments

![image](https://user-images.githubusercontent.com/39191/37426153-d428f7fe-2782-11e8-8158-aecb97509322.png)
 
and see it in the console drawer:
![image](https://user-images.githubusercontent.com/39191/37427877-d4ee17fa-2787-11e8-83e8-98fab0c3dacd.png)


Or use the command menu (ctrl-shift-p):

![image](https://user-images.githubusercontent.com/39191/37427890-dae1fb4a-2787-11e8-9031-eb1e42439f27.png)

**Comment by muelli** [comment]
Has this feature disappeared? I can't find it on my chromium 74.0.3729.169

**Comment by ZzEeKkAa** [comment]
> Has this feature disappeared? I can't find it on my chromium 74.0.3729.169

Just got same question. Solution:
https://chromedevtools.github.io/devtools-protocol/
