### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by copy** [ChromeDevTools/devtools-frontend#7]
Is it possible to support Firefox for the components that are independent of the backend? My use case is that I have a tool that creates .cpuprofile files, and it would be useful to allow viewing them in Firefox too (in a web application based on this project, that is).

**Comment by paulirish** [comment]
I think the answer here is "this is unlikely." 

It might be possible to do once, but I think it's unlikely that it wouldn't regress on a continuous basis. That said, once might be fine so if you (or someone) wanted to fork the frontend and slice down enough to view cpu profiles, then it might be straightforward to add FF support.
