### ISSUE TITLE
This mirrored repo is currently stalled and not being updated.

### ISSUE THREAD

**Issue by paulirish** [ChromeDevTools/devtools-frontend#72]
There was a big rename of Blink files within the Chromium repo: https://groups.google.com/a/chromium.org/d/msg/blink-dev/ysmSWdatQcM/tb6n4ZxhBAAJ

As such, the scripts to keep this mirror updated have broke.
So currently, it's frozen with last week's content. And the NPM package will rename frozen for a bit too.

The current devtools source of truth lives here: https://chromium.googlesource.com/chromium/src/+/master/third_party/blink/renderer/devtools/

We're working to get things restored (especially trying to maintain history).
I'll close this issue out when that's done.

**Comment by RReverser** [comment]
Yay, looks like it's fixed!

**Comment by paulirish** [comment]
This repo is now updated.  And the latest has been published to NPM as `1.0.555296`

Unfortunately we lost our git history. The previous branch is available here: [`pre_blink_move`](https://github.com/ChromeDevTools/devtools-frontend/tree/pre_blink_move)
