### ISSUE TITLE
option to hide screencast

### ISSUE THREAD

**Issue by czb** [ChromeDevTools/devtools-frontend#80]
Probably there should be somewhere an option to hide the `screencast` div element. For NodeJS debugging it is useless and just takes the valuable space on the screen.

![bug](https://user-images.githubusercontent.com/37391/41142691-d436cb24-6af6-11e8-9627-8bb8b19d848f.jpg)

**Comment by czb** [comment]
just found it. Stupid me...

**Comment by matt-** [comment]
I cant seem to fid this either? What was it?
