### ISSUE TITLE
Audits stuck at 'Lighthouse is warming up'

### ISSUE THREAD

**Issue by tyler36** [ChromeDevTools/devtools-frontend#84]
Updated to Chrome Version 68.0.3440.75 (Official Build) (64-bit) this morning and can no longer run audits.

Clicking 'Run audits' displays 'Lighthouse is warming up'. Nothing changes after waiting 3 minutes.
Clicking 'Cancel' changes the mseesage to 'cancelling' but nothing else changes after waiting 3 minutes.

Tried toggling mobile / desktop, various combinations of audits, toggling throttle speeds, and toggling storage.
Tried various websites such as:
https://github.com/
https://google.com

Tried uninstalling / reinstalling Chrome. 
Tried system restart.

OS: Win10 x64

**Comment by Ionaru** [comment]
I'm having the same issue with version 68.0.3440.75 (Official Build) (64-bit) for Linux Ubuntu

**Comment by Nojil** [comment]
Having the exact same issue after updating this morning to:

Version 68.0.3440.75 (Official Build) (64-bit)

**Comment by tyler36** [comment]
Tested this morning and works.

Seems like there might have been a missing asset that has now been found. See #69
